version: '3.8'

services:
  api:
    build: .
    container_name: rate_limiter_api
    restart: always
    environment:
      - PORT=5000
    expose:
      - "5000"
    networks:
      - app_network

  nginx:
    image: nginx:1.25
    container_name: rate_limiter_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge